png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
with(SelectedData, {
        plot(DateTime, Global_active_power, type = "l", ylab="Global Active Power")
        plot(DateTime, Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
        plot(DateTime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
        lines(DateTime, Sub_metering_2, col = "red")
        lines(DateTime, Sub_metering_3, col = "blue")
        legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, lwd = 2.5, col = c("black", "red", "blue"))
        plot(DateTime, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")             
})
dev.off()